@startuml
'https://plantuml.com/sequence-diagram

autonumber 1.1

participant scheduler
participant "commission forecast service" as CFS
participant "redis cache" as RC
participant "currency exchange api" as CEA
participant "commission forecast db" as CFDB

scheduler -> CFS: Scheduled to trigger at 12:01 mid night
CFS -> CFDB: Fetch all client records
    loop through all client records
        CFS -> RC: Fetch exchange rate for the currency code
            return exchange rate
        CFS -> CFS: exchange rate not available in Redis Cache
        CFS -> CEA: Fetch exchange rate for the currency code 
            return exchange rate
        CFS -> RC: Store exchange rate against currency code
        CFS -> CFS: Recalculate the pending commission for client's jobs
        CFS -> CFDB: Store the commissions for each job to the forecast_commissions table
    end
@enduml